import type { BibleRules, BibleRuleset } from './bible-schema';

/**
 * Deterministic markdown rendering of the bible, produced server-side at
 * analysis time and stored on the version row. Generated by code — not by the
 * model — so the same rules always render the same document and the review
 * screen never shows drift the rules don't contain.
 */
export function renderBibleMarkdown(rules: BibleRules): string {
  const md: string[] = [];

  for (const ruleset of rules.rulesets) {
    md.push(`# ${ruleset.title_nl}`);
    md.push(
      `*Van toepassing op: ${ruleset.applies_to.case_types.join(', ')} — scenario: ${ruleset.applies_to.scenario}*`,
    );
    if (ruleset.legal_basis.length > 0) {
      md.push(
        `*Wettelijke basis: ${ruleset.legal_basis.map((b) => `${b.law} ${b.article}`).join('; ')}*`,
      );
    }
    md.push('');
    renderRulesetBody(md, ruleset);
  }

  if (rules.glossary.length > 0) {
    md.push('# Begrippenlijst', '');
    for (const entry of rules.glossary) {
      md.push(`- **${entry.term}** — ${entry.definition_nl}`);
    }
    md.push('');
  }

  if (rules.open_questions.length > 0) {
    md.push('# ⚠ Open vragen van de AI', '');
    md.push(
      '*Deze punten kon de AI niet met zekerheid uit de documenten halen. Beoordeel ze voordat u deze versie activeert.*',
      '',
    );
    for (const question of rules.open_questions) {
      md.push(`- ${question}`);
    }
    md.push('');
  }

  return md.join('\n');
}

function renderRulesetBody(md: string[], ruleset: BibleRuleset): void {
  if (ruleset.checklist.length > 0) {
    md.push('## Checklist (aan te leveren)', '');
    md.push('| # | Document | Verplicht | Categorie | Controle |', '|---|---|---|---|---|');
    for (const item of ruleset.checklist) {
      md.push(
        `| \`${item.id}\` | ${item.label_nl}${item.notes_nl ? ` — *${item.notes_nl}*` : ''} | ${item.required ? 'ja' : 'nee'} | ${item.document_category} | ${item.verification} |`,
      );
    }
    md.push('');
  }

  if (ruleset.criteria.length > 0) {
    md.push('## Toetsingscriteria', '');
    for (const criterion of ruleset.criteria) {
      md.push(
        `### \`${criterion.id}\` — ${criterion.question_nl}`,
        `- **Type:** ${criterion.answer_type}${criterion.enum_values ? ` (${criterion.enum_values.join(' / ')})` : ''} · **Zwaarte:** ${criterion.severity === 'blocking' ? 'blokkerend' : 'adviserend'}`,
        `- **Voldoet:** ${criterion.assessment.pass_if_nl}`,
        `- **Voldoet niet:** ${criterion.assessment.fail_if_nl}`,
      );
      if (criterion.assessment.escalate_if_nl) {
        md.push(`- **Escaleren:** ${criterion.assessment.escalate_if_nl}`);
      }
      md.push(`- **Bron:** ${criterion.source.document} — "${criterion.source.reference}"`, '');
    }
  }

  if (ruleset.thresholds.length > 0) {
    md.push('## Drempelwaarden', '');
    md.push('| # | Indicator | Grens | Actie | Bron |', '|---|---|---|---|---|');
    for (const threshold of ruleset.thresholds) {
      md.push(
        `| \`${threshold.id}\` | ${threshold.name_nl} | ${threshold.comparator} ${threshold.value} ${threshold.unit} | ${threshold.action_if_met_nl} | ${threshold.source.document} (${threshold.source.reference}) |`,
      );
    }
    md.push('');
  }

  if (ruleset.routing.length > 0) {
    md.push('## Doorverwijzing & advies', '');
    for (const rule of ruleset.routing) {
      md.push(`- **Als:** ${rule.trigger_nl} → **dan:** ${rule.action_nl} *(naar: ${rule.recipient})*`);
    }
    md.push('');
  }

  if (ruleset.procedures.length > 0) {
    md.push('## Werkwijzen', '');
    for (const procedure of ruleset.procedures) {
      md.push(`### ${procedure.name_nl}`);
      procedure.steps_nl.forEach((step, index) => {
        md.push(`${index + 1}. ${step}`);
      });
      md.push('');
    }
  }
}
